apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-app
        image: nginx:latest
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
