apiVersion: v1
kind: Service
metadata:
  name: simple-nginx-gke
  labels:
    name: simple-nginx-gke
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: simple-nginx-gke
  type: LoadBalancer
