apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    creation_method: manual
    env: stage
    version: v1
spec:
  containers:
  - image: guigo13/web-server-image:v1
    name: nginx
    ports:
      - containerPort: 80
        protocol: TCP