SELECT COLUMN_NAME, ORDINAL_POSITION, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM information_schema.columns
WHERE 
	TABLE_CATALOG = 'ODS' AND
	TABLE_SCHEMA = 'dbo' AND
	TABLE_NAME = 'sourceSales'